[pytest]
pythonpath = .
markers = 
    unit: tests for single modules
    integration: test for communication between modules
    endToEnd: tests for entire workflows
    smoke: fast tests to check overall system integrity
